# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TFTI_Final_Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TFTI_Final_Project

  target 'TFTI_Final_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TFTI_Final_ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod ‘Firebase/Database’

end
